only:
  triggerType:
    - pullRequest
    - push
  triggerBranch:
    prTargetBranch:
      - ^master$
    pushOriginalBranch:
      - ^master$

onlyExecuteLastPipeline: true

stages:
  - Check
  - Release

STC:
  stage: Check
  plugin: STC
  pluginConfig:
    checkPoints: alipay
  checkRule:
    - stc = 0
  allowFailure: true

PMD:
  stage: Check
  plugin: PMD
  pluginConfig:
    encoding: UTF-8
    excludes:
      - "**/test/**"
    enableAdditional: true
  checkRule:
    - pmd1 = 0 && pmd2 = 0
  allowFailure: true

Build:
  stage: Check
  steps:
    - plugin: clone
    - plugin: cache
      inputs:
        type: restore
        key: maven-repo-{{ checksum 'pom.xml' }}
    - plugin: shell
      inputs:
        image: reg.docker.alibaba-inc.com/antb/sofaboot-build:1.0.0
        command: |
          export PATH=$PATH:/opt/taobao/java/bin:/opt/taobao/maven/bin
          java -version
          mvn -version
          cd $WORKSPACE
          mvn -U -Dmaven.test.skip=true -Dfile.encoding=UTF8 -Dmaven.repo.local=.mvn_repo package
    - plugin: cache
      inputs:
        type: upload
        key: maven-repo-{{ checksum 'pom.xml' }}
        paths: .mvn_repo

Release to Github:
  stage: Release
  steps:
    - plugin: clone
    - plugin: shell
      inputs:
        command: |
          rm .aci.yml
          rm .push_to_github_aci.yml
          rm .deploy_to_sonatype_aci.yml
          rm deploy_settings.xml
          rm zoloz.pgp
          rm README_INTERNAL.md
          rm pom.xml.internal
          TITLE=$(git rev-list --pretty=oneline --max-count=1 ${ACI_COMMIT_SHA} | cut -d' ' -f2-)
          git clone https://zolozAdmin:${ACI_VAR_github_password}@github.com/zoloz-pte-ltd/zoloz-api-sdk.git ../tmp
          rm -rf ../tmp/*
          cp -R -n * ../tmp/
          cd ../tmp/
          git config user.email "zoloz-github@antgroup.com"
          git config user.name "zolozAdmin"
          git add .
          git commit -m "$TITLE"
          git push origin
  only:
    triggerType:
      - push
    triggerBranch:
      pushOriginalBranch:
        - ^master$

deploy to sonatype:
  stage: Release
  steps:
    - plugin: clone
    - plugin: shell
      inputs:
        image: reg.docker.alibaba-inc.com/antb/sofaboot-build:1.0.0
        command: |
          export PATH=$PATH:/opt/taobao/java/bin:/opt/taobao/maven/bin
          java -version
          mvn -version
          cd $WORKSPACE
          gpg --import zoloz.pgp
          gpg --list-keys
          gpg --version
          gpg --list-secret
          export $(tty)
          mvn -Dfile.encoding=UTF8 -Dsonatype.password="${ACI_VAR_sonatype_password}" -Dgpg.passphrase=${ACI_VAR_gpg_passphrase} -s deploy_settings.xml clean deploy
  only:
    triggerType:
      - push
    triggerBranch:
      pushOriginalBranch:
        - ^master$

deployAliPayTestRepo:
  stage: Release
  plugin: ANT-BUILD
  pluginConfig:
    image: reg.docker.alibaba-inc.com/antb/jarbuild:0.0.1
    script:
      - |
        rm pom.xml
        cp pom.xml.internal pom.xml
        mvn  deploy -DskipTests -DskipTests=true  -s /opt/taobao/maven_settings/settings-release.xml -DaltDeploymentRepository=maven-release::default::http://mvn.test.alipay.net/artifactory/content/repositories/maven-snapshot/
  only:
    triggerType:
      - push
    triggerBranch:
      pushOriginalBranch:
        - ^master$

notifications:
  "开源代码发布成功":
    acting:
      - Release to Github
    channels:
      - https://oapi.dingtalk.com/robot/send?access_token=29caca4b9a9d30bd250ed8b724e2a1f87a94bd07490cae4d87181312652cae2d
    level: JOB
    template: AWS JOB ${ACI_JOB_NAME} SUCCESS [ ${ACI_COMMIT_REF_NAME}-${ACI_COMMIT_SHA}-${ACI_COMMIT_TITLE} ] ACI Pipeline详情：${ACI_PIPELINE_URL}
    type: DINGTALK
    when: SUCCESS
    at:
      - 矩诗
      - 蘭琪
      - +65-98636803

  "开源代码发布失败":
    acting:
      - Check
      - Build
      - Release to Github
    channels:
      - https://oapi.dingtalk.com/robot/send?access_token=29caca4b9a9d30bd250ed8b724e2a1f87a94bd07490cae4d87181312652cae2d
    level: JOB
    template: AWS JOB ${ACI_JOB_NAME} FAIL [ ${ACI_COMMIT_REF_NAME}-${ACI_COMMIT_SHA}-${ACI_COMMIT_TITLE} ] ACI Pipeline 运行失败，看看你干了什么好事！Pipeline详情：${ACI_PIPELINE_URL}
    type: DINGTALK
    when: FAIL
    at:
      - 矩诗
      - 蘭琪
      - +65-98636803
