onlyExecuteLastPipeline: true

stages:
  - Release

Release to Github:
  stage: Release
  steps:
    - plugin: clone
    - plugin: shell
      inputs:
        command: |
          rm .aci.yml
          rm .push_to_github_aci.yml
          rm .deploy_to_sonatype_aci.yml
          rm deploy_settings.xml
          rm zoloz.pgp
          rm README_INTERNAL.md
          rm pom.xml.internal
          TITLE=$(git rev-list --pretty=oneline --max-count=1 ${ACI_COMMIT_SHA} | cut -d' ' -f2-)
          git clone https://zolozAdmin:${ACI_VAR_github_password}@github.com/zoloz-pte-ltd/zoloz-api-sdk.git ../tmp
          rm -rf ../tmp/*
          cp -R -n * ../tmp/
          cd ../tmp/
          git config user.email "zoloz-github@antgroup.com"
          git config user.name "zolozAdmin"
          git add .
          git commit -m "$TITLE"
          git push origin
  pluginConfig:
    approvalButtonName: '确认'
    approvers:
      - jushi.zf
      - jingwei.yang
      - lan.qi
  only:
    triggerType:
      - push
    triggerBranch:
      pushOriginalBranch:
        - ^master$

notifications:
  "开源代码发布成功":
    acting:
      - Release to Github
    channels:
      - https://oapi.dingtalk.com/robot/send?access_token=29caca4b9a9d30bd250ed8b724e2a1f87a94bd07490cae4d87181312652cae2d
    level: JOB
    template: AWS JOB ${ACI_JOB_NAME} SUCCESS [ ${ACI_COMMIT_REF_NAME}-${ACI_COMMIT_SHA}-${ACI_COMMIT_TITLE} ] ACI Pipeline详情：${ACI_PIPELINE_URL}
    type: DINGTALK
    when: SUCCESS
    at:
      - 矩诗
      - 蘭琪
      - +65-98636803

  "开源代码发布失败":
    acting:
      - Check
      - Build
      - Release to Github
    channels:
      - https://oapi.dingtalk.com/robot/send?access_token=29caca4b9a9d30bd250ed8b724e2a1f87a94bd07490cae4d87181312652cae2d
    level: JOB
    template: AWS JOB ${ACI_JOB_NAME} FAIL [ ${ACI_COMMIT_REF_NAME}-${ACI_COMMIT_SHA}-${ACI_COMMIT_TITLE} ] ACI Pipeline 运行失败，看看你干了什么好事！Pipeline详情：${ACI_PIPELINE_URL}
    type: DINGTALK
    when: FAIL
    at:
      - 矩诗
      - 蘭琪
      - +65-98636803
