only:
  triggerType:
    - pullRequest
    - push
  triggerBranch:
    prTargetBranch:
      - ^master$
    pushOriginalBranch:
      - ^master$

onlyExecuteLastPipeline: true

stages:
  - Prepare
  - Check
  - Release

STC:
  stage: Check
  plugin: STC
  pluginConfig:
    checkPoints: alipay
  checkRule:
    - stc = 0
  allowFailure: false

PMD:
  stage: Check
  plugin: PMD
  pluginConfig:
    encoding: UTF-8
    excludes:
      - "**/test/**"
    enableAdditional: true
  checkRule:
    - pmd1 = 0 && pmd2 = 0
  allowFailure: true

Build:
  stage: Check
  steps:
    - plugin: clone
    - plugin: cache
      inputs:
        type: restore
        key: maven-repo-{{ checksum 'pom.xml' }}
    - plugin: shell
      inputs:
        image: reg.docker.alibaba-inc.com/antb/sofaboot-build:1.0.0
        command: |
          export PATH=$PATH:/opt/taobao/java/bin:/opt/taobao/maven/bin
          java -version
          mvn -version
          cd $WORKSPACE
          mvn -U -Dmaven.test.skip=true -Dfile.encoding=UTF8 -Dmaven.repo.local=.mvn_repo package
    - plugin: cache
      inputs:
        type: upload
        key: maven-repo-{{ checksum 'pom.xml' }}
        paths: .mvn_repo

Release to Github:
  stage: Release
  steps:
    - plugin: clone
    - plugin: shell
      inputs:
        command: |
          set +x
          git remote add github https://zolozAdmin:${ACI_VAR_github_password}@github.com/zoloz-pte-ltd/zoloz-api-sdk.git
          set -x
          git fetch github
          git checkout -b release-to-github github/master
          git checkout ${ACI_COMMIT_SHA} -- .
          git rm --cached .push_to_github_aci.yml
          git config user.email "zoloz-github@antgroup.com"
          git config user.name "zolozAdmin"
          git commit -m "$(git rev-list --pretty=oneline --max-count=1 ${ACI_COMMIT_SHA} | cut -d' ' -f2-)"
          set +x
          git push --set-upstream github release-to-github:master
          set -x
  pluginConfig:
    approvalButtonName: '确认'
    approvers:
      - jushi.zf
      - jingwei.yang
      - lan.qi
  only:
    triggerType:
      - push
    triggerBranch:
      pushOriginalBranch:
        - ^master$

notifications:
  "开源代码发布成功":
    acting:
      - Release to Github
    channels:
      - https://oapi.dingtalk.com/robot/send?access_token=93789a7deb3dadc51a993b97fd5088d00d13ff86660a91d13d637dc39d18b761
    level: JOB
    template: JOB ${ACI_JOB_NAME} SUCCESS [ ${ACI_COMMIT_REF_NAME}-${ACI_COMMIT_SHA}-${ACI_COMMIT_TITLE} ] ACI Pipeline详情：${ACI_PIPELINE_URL}
    type: DINGTALK
    when: SUCCESS
    at:
      - 矩诗
      - 蘭琪
      - +65-98636803

  "开源代码发布失败":
    acting:
      - Check
      - Build
      - Release to Github
    channels:
      - https://oapi.dingtalk.com/robot/send?access_token=93789a7deb3dadc51a993b97fd5088d00d13ff86660a91d13d637dc39d18b761
    level: JOB
    template: JOB ${ACI_JOB_NAME} FAIL [ ${ACI_COMMIT_REF_NAME}-${ACI_COMMIT_SHA}-${ACI_COMMIT_TITLE} ] ACI Pipeline 运行失败，看看你干了什么好事！Pipeline详情：${ACI_PIPELINE_URL}
    type: DINGTALK
    when: FAIL
    at:
      - 矩诗
      - 蘭琪
      - +65-98636803
